# Generated by Django 3.1.2 on 2020-10-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=30)),
                ('bill_type', models.IntegerField(choices=[(1, 'Acueducto'), (2, 'Alcantarillado'), (3, 'Administración'), (4, 'Energía')], default=1)),
                ('items', models.ManyToManyField(to='testbills.Item')),
            ],
        ),
    ]
